### ISSUE TITLE
Make Touchegg-gce "make-able" in Focal / modern distros

### ISSUE THREAD

**Issue by marticster** [Raffarti/Touchegg-gce#16]
libqt4-dev is required to make touchegg-gce, however libqt4-dev is obsolete and was dropped since Ubuntu 19.1, superseded by QT5. There is no release candidate for libqt4-dev.

**Comment by Raffarti** [comment]
Hello, thank for the interest. Touchegg-gce should work just fine with Qt5. If have issues with Qt5 please report those instead.
