### ISSUE TITLE
Change actions, removes them 

### ISSUE THREAD

**Issue by fuelflo** [Raffarti/Touchegg-gce#6]
Hey, i got following issuses using touchegg-gce on Ubuntu 14.10 and Mint 17.1, both 64bit.

When editing an existing action it disappears completely after clicking OK So there is no effective way to edit them. The only way is to delete it and create a new one.

**Comment by Raffarti** [comment]
Fixed. Sorry about that, this project should be remade anew, it looks like spaghetti...

**Comment by fuelflo** [comment]
Thx for the quick fix!

...jeah i can imagine that...but as we all know spare time is usually pretty rare :D

**Comment by fuelflo** [comment]
P.S. ...I'm quite new to github...but i'd like to contribute some german translations...whats the best way to to that?

**Comment by Raffarti** [comment]
I'm not so seasoned on the matter myself. As far as I can tell:
a) Fork my repo in your account.
b) Commit you changes.
c) Make a pull request on my repo.
For any futher question that doesn't need to be on github, you can look for me at #konversation channel in freenode IRC or email me.
